Attribute VB_Name = "lanscript"
Public langutvonal$, langszint%, utfrmnev$, langhun%
Public langform$(200), langment$(200, 20), langprg$(250), langmodul$(1000), spar$(20), spdb%

Public Sub prglang(frmnev$)
  langszint% = 1
  Call langut
  Call langinit(frmnev$, 1)
  Call langinit(frmnev$, 2)
  Call langinit("modul", 3)
  Call szkriptel(frmnev$)
End Sub

Public Sub frmlang(frmnev$)
  Call langinit(frmnev$, 2)
  Call szkriptel(frmnev$)
End Sub

Public Sub langut()
  lanfi = FreeFile
  Open "C:\auwin\auw-lang.par" For Binary Shared As #lanfi
  langfilm& = LOF(lanfi)
  Close lanfi
  If langfilm& > 0 Then
    lanfi = FreeFile
    Open "C:\auwin\auw-lang.par" For Input As #lanfi
    Input #lanfi, langsorsz%
    Close lanfi
    langhun% = 1
    Select Case langsorsz%
      Case 1: langutvonal = "C:\auwin\lang\hun\":
      Case 2: langutvonal = "C:\auwin\lang\eng\": langhun% = 2
      Case 3: langutvonal = "C:\auwin\lang\ger\": langhun% = 3
      Case 4: langutvonal = "C:\auwin\lang\srb\": langhun% = 4
      Case 5: langutvonal = "C:\auwin\lang\cro\": langhun% = 5
      Case 6: langutvonal = "C:\auwin\lang\chi\": langhun% = 6
      Case Else: langutvonal = "C:\auwin\lang\hun\": langhun% = 1
    End Select
    alfag$ = Dir(langutvonal$)
    If alfag$ = "" Then
      langutvonal$ = "C:\auwin\"
    End If
  Else
    langutvonal$ = "C:\auwin\"
  End If
End Sub

Public Sub langinit(frmnev$, frmod%)
  '--- tömbök feltöltése
  '--- frmnev form vagy programneve vagy modul
  '--- frmod%=1 program (langprg tömb)
  '--- frmod%=2 form (langform$ tömb)
  '--- frmod%=3 modul (langmodul$ tömb)
  utfrmnev$ = frmnev$
  If frmod% = 2 Then
    For iiii4% = 1 To 200
      langment$(iiii4%, langszint%) = langform$(iiii4%)
    Next
    langszint% = langszint% + 1
  End If
  scfil = FreeFile
  If frmod% = 1 Then
    Open langutvonal$ + "auwin.pln" For Input As #scfil
  Else
    Open langutvonal$ + "auwin.lan" For Input As #scfil
  End If
  elkezdte% = 0
  Do
    Line Input #scfil, scrp$
    If Left(scrp$, 1) <> "*" Then
      Call scpar(scrp$, "\")
      If UCase(spar(1)) = UCase(frmnev$) And Val(spar(2)) = frmod% Then
        elkezdte% = 1
        If frmod% = 1 Then
          langprg(Val(spar(3))) = spar(4)
        Else
          If frmod% = 2 Then
            langform(Val(spar(3))) = spar(4)
          Else
            langmodul(Val(spar(3))) = spar(4)
          End If
        End If
      Else
        If elkezdte% = 1 Then Exit Do
      End If
    End If
  Loop While Not EOF(scfil)
  Close scfil
End Sub

Public Sub langclos()
  langszint% = langszint% - 1
  If langszint% < 0 Then langszint% = 0
  If langszint% > 0 Then
    For iiii4% = 1 To 200
      langform$(iiii4%) = langment(iiii4%, langszint%)
    Next
  End If
End Sub

Public Sub szkriptel(frmnev$)
  Select Case frmnev$
    Case "auw-gsml"
      form1.Label12.Caption = langform(1)
      form1.Label13.Caption = langform(2)
      form1.Label9.Caption = langform(3)
      form1.Label10.Caption = langform(4)
      form1.Label11.Caption = langform(5)
      form1.Command15.Caption = langform(6)
      form1.Command16.Caption = langform(7)
      form1.Command17.Caption = langform(8)
    Case "Msnyom"
      Msnyom.Caption = langform(1)
      Msnyom.Option1.Caption = langform(2)
      Msnyom.Option3.Caption = langform(3)
      Msnyom.Option2.Caption = langform(4)
      Msnyom.Option4.Caption = langform(5)
      Msnyom.Option5.Caption = langform(6)
      Msnyom.Option6.Caption = langform(7)
      Msnyom.Option7.Caption = langform(8)
      Msnyom.Check6.Caption = langform(9)
      Msnyom.Check1.Caption = langform(10)
      Msnyom.Check4.Caption = langform(11)
      Msnyom.Check2.Caption = langform(12)
      Msnyom.Check3.Caption = langform(13)
      Msnyom.Check5.Caption = langform(14)
      Msnyom.Check7.Caption = langform(15)
      Msnyom.Check8.Caption = langform(16)
      Msnyom.Command1.Caption = langform(17)
      Msnyom.Command2.Caption = langform(18)
    Case "Mesbox"
      Mesbox.Command1.Caption = langform(1)
      Mesbox.Command2.Caption = langform(2)
      Mesbox.Command3.Caption = langform(3)
    Case "auw"
      form1.Label1.Caption = langform(1)
      form1.Label2.Caption = langform(2)
      form1.Command1.Caption = langform(3)
      form1.Command2.Caption = langform(4)
      form1.Command3.Caption = langform(5)
    Case "szenged"
      Szenged.Caption = langform(1)
      Szenged.Label1.Caption = langform(2)
      Szenged.Label3.Caption = langform(3)
      Szenged.Command1.Caption = langform(4)
    Case "csvbev"
      Csvbev.Caption = langform(1)
      Csvbev.Command1.Caption = langform(2)
      Csvbev.Command2.Caption = langform(3)
      Csvbev.Label1.Caption = langform(4)
      Csvbev.Label2.Caption = langform(5)
      Csvbev.Label3.Caption = langform(6)
      Csvbev.Label4.Caption = langform(7)
      Csvbev.Label5.Caption = langform(8)
      Csvbev.Label6.Caption = langform(9)
    Case "languag"
      Form3.Command1.Caption = langform(1)
      Form3.Command2.Caption = langform(2)
      Form3.Caption = langform(3)
    Case "ervkod"
      Form2.Label1.Caption = langform(1)
      Form2.Command1.Caption = langform(2)
      Form2.Command2.Caption = langform(3)
    Case "cegek"
      Cegek.Caption = langform(1)
      Cegek.Command1.Caption = langform(2)
      Cegek.Command2.Caption = langform(3)
      Cegek.Command1.ToolTipText = langform(4)
      Cegek.Command2.ToolTipText = langform(5)
    Case "nevjegy"
      Nevjegy.Label1.Caption = langform(1)
      Nevjegy.Label2.Caption = langform(2)
      Nevjegy.Label3.Caption = langform(3)
      Nevjegy.Label4.Caption = langform(4)
      Nevjegy.Label5.Caption = langform(5)
      Nevjegy.Label6.Caption = langform(6)
      Nevjegy.Label7.Caption = langform(7)
    Case "auwstark"
      Auwstart.Label1.Caption = langform(1)
      Auwstart.Label2.Caption = langform(2)
      Auwstart.Label3.Caption = langform(3)
      Auwstart.Label4.Caption = langform(4)
      Auwstart.Label5.Caption = langform(5)
      Auwstart.Label6.Caption = langform(6)
      Auwstart.Label7.Caption = langform(7)
      Auwstart.Label13.Caption = langform(8)
      Auwstart.Command1.ToolTipText = langform(9)
      Auwstart.Command2.ToolTipText = langform(10)
      Auwstart.Command3.ToolTipText = langform(11)
      Auwstart.Command4.ToolTipText = langform(12)
      Auwstart.Command5.ToolTipText = langform(13)
      Auwstart.Command6.ToolTipText = langform(14)
      Auwstart.Command7.ToolTipText = langform(15)
      Auwstart.Command9.Caption = langform(17)
      Auwstart.Command10.Caption = langform(16)
    Case "hash"
      Hash.Caption = langform(1)
      Hash.Command1.Caption = langform(2)
      Hash.Command2.Caption = langform(3)
    Case "inrutin"
      Inrutin.Label1.Caption = langform(1)
      Inrutin.Command1.Caption = langform(2)
      Inrutin.Command2.Caption = langform(3)
    Case "kereso"
      Kereso.Caption = langform(1)
      Kereso.Text2.Text = langform(2)
      Kereso.Text3.Text = langform(3)
      Kereso.Frame2.Caption = langform(10)
      Kereso.Frame1.Caption = langform(1)
      Kereso.Command7.Caption = langform(4)
      Kereso.Command8.Caption = langform(5)
      Kereso.Command9.Caption = langform(6)
      Kereso.Command11.Caption = langform(7)
      Kereso.Command10.Caption = langform(8)
      Kereso.Command6.Caption = langform(9)
      Kereso.Command7.ToolTipText = langform(11)
      Kereso.Command8.ToolTipText = langform(12)
      Kereso.Command9.ToolTipText = langform(13)
      Kereso.Command11.ToolTipText = langform(14)
      Kereso.Command10.ToolTipText = langform(15)
      Kereso.Command6.ToolTipText = langform(16)
    Case "komind"
      Komind.Caption = langform(1)
      Komind.Command3.Caption = langform(2)
      Komind.Command2.Caption = langform(3)
      Komind.Command1.Caption = langform(4)
    Case "tabla"
      Tabla.Command1.Caption = langform(1)
      Tabla.Command2.Caption = langform(2)
      Tabla.Command3.Caption = langform(3)
      Tabla.Command4.Caption = langform(4)
      Tabla.Command1.ToolTipText = langform(5)
      Tabla.Command2.ToolTipText = langform(6)
      Tabla.Command3.ToolTipText = langform(7)
      Tabla.Command4.ToolTipText = langform(8)
      Tabla.Caption = langform(9)
      Tabla.Text2.ToolTipText = langform(10)
    Case "torlnyug"
      Torlnyug.Caption = langform(1)
      Torlnyug.Label1.Caption = langform(5)
      Torlnyug.Label2.Caption = langform(2)
      Torlnyug.Command1.Caption = langform(3)
      Torlnyug.Command2.Caption = langform(4)
    Case "vektor"
      Vektor.Caption = langform(1)
      Vektor.Command2.Caption = langform(2)
      Vektor.Command3.Caption = langform(3)
      Vektor.Command1.Caption = langform(4)
      Vektor.Command2.ToolTipText = langform(5)
      Vektor.Command3.ToolTipText = langform(6)
      Vektor.Command1.ToolTipText = langform(7)
      Vektor.Text2.ToolTipText = langform(8)
    Case "kodok"
      Kodok.Caption = langform(1)
    Case "karton"
      karton.Caption = langform(1)
      karton.Command1.Caption = langform(2)
      karton.Command2.Caption = langform(3)
      karton.Command3.Caption = langform(4)
      karton.Command4.Caption = langform(5)
      karton.MSFlexGrid1.ToolTipText = langform(6)
      karton.Command1.ToolTipText = langform(11)
      karton.Command2.ToolTipText = langform(12)
      karton.Command3.ToolTipText = langform(13)
      karton.Command4.ToolTipText = langform(14)
    Case "arfkon"
      Arfkon.Option1.Caption = langform(1)
      Arfkon.Option2.Caption = langform(2)
      Arfkon.Option3.Caption = langform(3)
      Arfkon.Option4.Caption = langform(4)
      Arfkon.Option5.Caption = langform(5)
      Arfkon.Option6.Caption = langform(6)
      Arfkon.Frame1.Caption = langform(9)
      Arfkon.Label1.Caption = langform(9)
      Arfkon.Label2.Caption = langform(7)
      Arfkon.Label3.Caption = langform(8)
      Arfkon.Command1.Caption = langform(10)
      Arfkon.Command2.Caption = langform(11)
    Case "rendezo"
      rendezo.Caption = langform(1)
      rendezo.Command1.Caption = langform(2)
      rendezo.Command2.Caption = langform(3)
    Case "sztorno"
      Sztorno.Caption = langform(10)
      Sztorno.Label1.Caption = langform(1)
      Sztorno.Label2.Caption = langform(2)
      Sztorno.Label3.Caption = langform(3)
      Sztorno.Label4.Caption = langform(4)
      Sztorno.Frame1.Caption = langform(5)
      Sztorno.Option1.Caption = langform(6)
      Sztorno.Option2.Caption = langform(7)
      Sztorno.Command1.Caption = langform(8)
      Sztorno.Command2.Caption = langform(9)
    Case "armeg"
      armeg.Caption = langform(1)
      armeg.Label1.Caption = langform(2)
      armeg.Command1.Caption = langform(3)
    Case "bankval"
      Bankval.Caption = langform(1)
      Bankval.Command1.Caption = langform(2)
      Bankval.Command2.Caption = langform(3)
      Bankval.Label1.Caption = langform(4)
    Case "bovslev"
      bovslev.Caption = langform(1)
      bovslev.Label1.Caption = langform(2)
      bovslev.Label2.Caption = langform(5)
      bovslev.Label3.Caption = langform(4)
      bovslev.Label4.Caption = langform(3)
      bovslev.Command1.Caption = langform(6)
    Case "kerkesz"
      kerkesz.Caption = langform(1)
      kerkesz.Command1.Caption = langform(2)
    Case "megnbeal"
      megnbeal.Caption = langform(1)
      megnbeal.Option1.Caption = langform(2)
      megnbeal.Option2.Caption = langform(2) + " 2."
      megnbeal.Option3.Caption = langform(2) + " 3."
      megnbeal.Option4.Caption = langform(3)
      megnbeal.Command1.Caption = langform(4)
    Case "bizonylat"
      Bizonylat.Caption = langform(187)
      Bizonylat.Command1.Caption = langform(188)
      Bizonylat.Command2.Caption = langform(189)
    Case "felstrn"
      Felstrn.Caption = langform(1)
      Felstrn.Label3.Caption = langform(2)
      Felstrn.Label5.Caption = langform(3)
      Felstrn.Label1.Caption = langform(4)
      Felstrn.Command1.Caption = langform(5)
      Felstrn.Command2.Caption = langform(6)
    Case "cdiras"
      Cdiras.Caption = langform(1)
      Cdiras.Label1.Caption = langform(2)
      Cdiras.Label2.Caption = langform(3)
      Cdiras.Command1.Caption = langform(1)
      Cdiras.Command2.Caption = langform(5)
      Cdiras.Command3.Caption = langform(4)
    Case "forit"
      forit.Caption = langform(1)
      'forit.Label1.Caption = langform(2)
      forit.Label2.Caption = langform(3)
      forit.Label3.Caption = langform(4)
    Case "szamlak"
      szamlak.Caption = langform(1)
      szamlak.Command1.Caption = "FIFO " + langform(2)
      szamlak.Command17.Caption = "LIFO " + langform(2)
      szamlak.Command2.Caption = langform(3)
      szamlak.Command3.Caption = langform(4)
      szamlak.Command16.Caption = langform(5)
      szamlak.Command4.Caption = langform(6)
      szamlak.Command5.Caption = langform(7)
      szamlak.Command6.Caption = langform(9)
      szamlak.Command7.Caption = langform(8)
      szamlak.Command8.Caption = "< 1000 " + langform(10)
      szamlak.Command9.Caption = "< 10000 " + langform(10)
      szamlak.Command10.Caption = "< 100000 " + langform(10)
      szamlak.Command11.Caption = "< 1000000 " + langform(10)
      szamlak.Command12.Caption = "> 1000 " + langform(10)
      szamlak.Command13.Caption = "> 10000 " + langform(10)
      szamlak.Command14.Caption = "> 100000 " + langform(10)
      szamlak.Command15.Caption = "> 1000000 " + langform(10)
    Case "szamrend"
      szamrend.Command1.Caption = langform(1)
      szamrend.Command2.Caption = langform(2)
      szamrend.Label1.Caption = langform(3)
      szamrend.Label2.Caption = langform(4)
      szamrend.Command5.Caption = langform(14)
      szamrend.Label3.Caption = langform(15)
      szamrend.Label4.Caption = langform(16)
      szamrend.Label5.Caption = langform(17)
      szamrend.Label6.Caption = langform(18)
      szamrend.Command3.Caption = langform(19)
      szamrend.Command4.Caption = langform(20)
    Case "kompenz"
      Kompenz.Command1.Caption = langform(1)
      Kompenz.Command2.Caption = langform(2)
      Kompenz.Label1.Caption = langform(3)
      Kompenz.Label2.Caption = langform(4)
      Kompenz.Command5.Caption = langform(14)
      Kompenz.Label3.Caption = langform(15)
      Kompenz.Label4.Caption = langform(16)
      Kompenz.Label5.Caption = langform(17)
      Kompenz.Label6.Caption = langform(18)
      Kompenz.Command3.Caption = langform(19)
      Kompenz.Command4.Caption = langform(20)
    Case "marvert"
      Marvert.Command1.Caption = langform(1)
      Marvert.Command2.Caption = langform(2)
      Marvert.Command3.Caption = langform(3)
      Marvert.Command4.Caption = langform(4)
      Marvert.Command5.Caption = langform(5)
      Marvert.Label1.Caption = langform(7)
      Marvert.Label2.Caption = langform(8)
      Marvert.Label3.Caption = langform(9)
      Marvert.Label4.Caption = langform(10)
    Case "erthat"
      Erthat.Label1.Caption = langform(1)
      Erthat.Label2.Caption = langform(2)
      Erthat.Command1.Caption = langform(3)
      Erthat.Command2.Caption = langform(4)
      Erthat.Caption = langform(5)
    Case "sztormod"
      sztormod.Command1.Caption = langform(1)
      sztormod.Command2.Caption = langform(2)
      sztormod.Label1.Caption = langform(3)
      sztormod.Label2.Caption = langform(4)
      sztormod.Label3.Caption = langform(5)
      sztormod.Caption = langform(6)
    Case "penzcsop"
      Penzcsop.Caption = langform(1)
      Penzcsop.Label2.Caption = langform(2)
      Penzcsop.Label4.Caption = langform(3)
      Penzcsop.Label6.Caption = langform(4)
      Penzcsop.Command1.Caption = langform(5)
      Penzcsop.Command2.Caption = langform(6)
    Case "fokozat"
      Fokozat.Caption = langform(1)
      Fokozat.Option1.Caption = langform(2)
      Fokozat.Option2.Caption = langform(3)
      Fokozat.Option3.Caption = langform(4)
      Fokozat.Option4.Caption = langform(5)
      Fokozat.Check1.Caption = langform(6)
    Case "ptzar"
      Ptzar.Caption = langform(1)
      Ptzar.Label1.Caption = langform(2)
      Ptzar.Command1.Caption = langform(3)
      Ptzar.Command2.Caption = langform(4)
    Case "mailsmtp"
      Mailsmtp.Caption = langform(1)
      Mailsmtp.Frame1.Caption = langform(2)
      Mailsmtp.Frame2.Caption = langform(11)
      Mailsmtp.Frame3.Caption = langform(12)
      Mailsmtp.Frame4.Caption = langform(13)
      Mailsmtp.Check1.Caption = langform(16)
      Mailsmtp.Check2.Caption = langform(17)
      Mailsmtp.Check3.Caption = langform(18)
      Mailsmtp.Check4.Caption = langform(9)
      Mailsmtp.Command1.Caption = langform(19)
      Mailsmtp.Command2.Caption = langform(20)
      Mailsmtp.Command3.Caption = langform(14)
      Mailsmtp.Label1.Caption = langform(3)
      Mailsmtp.Label2.Caption = langform(5)
      Mailsmtp.Label3.Caption = langform(21)
      Mailsmtp.Label4.Caption = langform(5)
      Mailsmtp.Label5.Caption = langform(7)
      Mailsmtp.Label6.Caption = langform(10)
      Mailsmtp.Label7.Caption = langform(8)
      Mailsmtp.Label8.Caption = langform(4)
      Mailsmtp.Label9.Caption = langform(4)
      Mailsmtp.Label10.Caption = langform(15)
      Mailsmtp.Label11.Caption = langform(6)
      Mailsmtp.Check1.ToolTipText = langform(36)
      Mailsmtp.Check2.ToolTipText = langform(37)
      Mailsmtp.Check3.ToolTipText = langform(38)
    Case "rkbizbe"
      RKBIZBE.Caption = langform(1)
      RKBIZBE.Label1.Caption = langform(2)
      RKBIZBE.Label2.Caption = langform(3)
      RKBIZBE.Command1.Caption = langform(4)
      RKBIZBE.Command2.Caption = langform(6)
      RKBIZBE.Command3.Caption = langform(5)
    Case "talloz"
      Talloz.Label1.Caption = langform(1)
      Talloz.Label2.Caption = langform(2)
      Talloz.Command1.Caption = langform(3)
      Talloz.Command2.Caption = langform(4)
    Case "sztornyug"
      Sztornyug.Caption = langform(1)
      Sztornyug.Label1.Caption = langform(2)
      Sztornyug.Label2.Caption = langform(3)
      Sztornyug.Command1.Caption = langform(4)
      Sztornyug.Command2.Caption = langform(5)
    Case "megrendel"
      Megrendel.Caption = langform(1)
      Megrendel.Label1.Caption = langform(2)
    Case "rtetel"
      Rtetel.Caption = langform(1)
      Rtetel.Command1.Caption = langform(2)
      Rtetel.Command2.Caption = langform(3)
    Case "felold"
      Felold.Command1.Caption = langform(1)
      Felold.Command2.Caption = langform(2)
    Case "ujceg"
      Ujceg.Command1.Caption = langform(1)
      Ujceg.Command2.Caption = langform(2)
      Ujceg.Option1.Caption = langform(3)
      Ujceg.Option2.Caption = langform(4)
      Ujceg.Option3.Caption = langform(5)
      Ujceg.Option4.Caption = langform(6)
      Ujceg.Check1.Caption = langform(7)
      Ujceg.Check2.Caption = langform(8)
      Ujceg.Check3.Caption = langform(9)
      Ujceg.Check4.Caption = langform(10)
      Ujceg.Check5.Caption = langform(11)
      Ujceg.Check6.Caption = langform(12)
      Ujceg.Check7.Caption = langform(13)
      Ujceg.Check8.Caption = langform(14)
      Ujceg.Check9.Caption = langform(15)
      Ujceg.Check10.Caption = langform(16)
      Ujceg.Check11.Caption = langform(17)
      Ujceg.Check12.Caption = langform(18)
      Ujceg.Caption = langform(19)
    Case "akcio"
      Akcio.Caption = langform(1)
      Akcio.Command1.Caption = langform(2)
      Akcio.Command2.Caption = langform(3)
      Akcio.Command3.Caption = langform(4)
      Akcio.Command4.Caption = langform(5)
      Akcio.Command5.Caption = langform(6)
      Akcio.Command6.Caption = langform(7)
      Akcio.Command7.Caption = langform(8)
    Case "csophossz"
      csophossz.Command1.Caption = langform(1)
      csophossz.Command2.Caption = langform(2)
      csophossz.Label1.Caption = langform(3)
      csophossz.Label2.Caption = langform(4)
      csophossz.Label3.Caption = langform(5)
      csophossz.Label4.Caption = langform(6)
      csophossz.Caption = langform(7)
    Case "csopmeg"
      csopmeg.Command1.Caption = langform(1)
      csopmeg.Command2.Caption = langform(2)
      csopmeg.Command3.Caption = langform(3)
      csopmeg.Option1.Caption = langform(4)
      csopmeg.Option2.Caption = langform(5)
      csopmeg.Option3.Caption = langform(6)
      csopmeg.Label1.Caption = langform(7)
      csopmeg.Caption = langform(8)
    Case "halmaz"
      Halmaz.Option1.Caption = langform(1)
      Halmaz.Option2.Caption = langform(2)
      Halmaz.Option3.Caption = langform(3)
      Halmaz.Option4.Caption = langform(4)
      Halmaz.Option5.Caption = langform(5)
      Halmaz.Option6.Caption = langform(6)
      Halmaz.Option7.Caption = langform(7)
      Halmaz.Option8.Caption = langform(8)
      Halmaz.Option9.Caption = langform(9)
      Halmaz.Option10.Caption = langform(10)
      Halmaz.Option11.Caption = langform(11)
      Halmaz.Option12.Caption = langform(12)
      Halmaz.Option13.Caption = langform(13)
      Halmaz.Option14.Caption = langform(14)
      Halmaz.Option15.Caption = langform(15)
      Halmaz.Option16.Caption = langform(16)
      Halmaz.Option17.Caption = langform(17)
      Halmaz.Option18.Caption = langform(18)
      Halmaz.Option19.Caption = langform(19)
      Halmaz.Option20.Caption = langform(20)
      Halmaz.Option21.Caption = langform(21)
      Halmaz.Option22.Caption = langform(22)
      Halmaz.Option23.Caption = langform(23)
      Halmaz.Option24.Caption = langform(24)
      Halmaz.Option25.Caption = langform(25)
      Halmaz.Option26.Caption = langform(26)
      Halmaz.Option27.Caption = langform(27)
      Halmaz.Option28.Caption = langform(28)
      Halmaz.Option29.Caption = langform(29)
      Halmaz.Check1.Caption = langform(30)
      Halmaz.Command1.Caption = langform(31)
      Halmaz.Command2.Caption = langform(32)
      Halmaz.Frame1.Caption = langform(33)
      Halmaz.Frame2.Caption = langform(34)
      Halmaz.Frame3.Caption = langform(35)
      Halmaz.Frame4.Caption = langform(36)
      Halmaz.Frame5.Caption = langform(37)
      Halmaz.Caption = langform(38)
      Halmaz.Label1.Caption = langform(39)
      Halmaz.Label2.Caption = langform(40)
    Case "filex"
      filex.Caption = langform(1)
      filex.Command1.Caption = langform(2)
      filex.Command2.Caption = langform(3)
      filex.Option1.Caption = langform(4)
      filex.Option2.Caption = langform(5)
      filex.Option3.Caption = langform(6)
      filex.Option4.Caption = langform(7)
      filex.Option5.Caption = langform(8)
      filex.Option6.Caption = langform(9)
      filex.Option7.Caption = langform(10)
      filex.Check1.Caption = langform(11)
      filex.Check2.Caption = langform(12)
      filex.Check3.Caption = langform(13)
      filex.Check4.Caption = langform(14)
      filex.Frame1.Caption = langform(15)
      filex.Frame2.Caption = langform(16)
      filex.Label1.Caption = langform(17)
    Case "tabkez"
      Tabkez.Caption = langform(1)
      Tabkez.Option1.Caption = langform(2)
      Tabkez.Option2.Caption = langform(3)
      Tabkez.Option3.Caption = langform(4)
      Tabkez.Option4.Caption = langform(5)
      Tabkez.Option5.Caption = langform(6)
      Tabkez.Option6.Caption = langform(7)
      Tabkez.Option7.Caption = langform(8)
      Tabkez.Check1.Caption = langform(9)
      Tabkez.Command1.Caption = langform(10)
      Tabkez.Command2.Caption = langform(11)
      Tabkez.Command3.Caption = langform(12)
      Tabkez.Command4.Caption = langform(13)
      Tabkez.Frame2.Caption = langform(15)
    Case "feltetel"
      Feltetel.Caption = langform(1)
      Feltetel.Command1.Caption = langform(2)
      Feltetel.Command2.Caption = langform(3)
    Case "wordkez"
      Wordkez.Caption = langform(1)
      Wordkez.Option1.Caption = langform(2)
      Wordkez.Option2.Caption = langform(3)
      Wordkez.Option3.Caption = langform(4)
      Wordkez.Frame1.Caption = langform(5)
      Wordkez.Label1.Caption = langform(6)
      Wordkez.Command1.Caption = langform(7)
      Wordkez.Command2.Caption = langform(8)
      Wordkez.Command3.Caption = langform(9)
      Wordkez.Command4.Caption = langform(10)
    Case "nyvany"
      nyvany.Caption = langform(3)
      nyvany.Command1.Caption = langform(1)
      nyvany.Command2.Caption = langform(2)
    Case "nyomtat"
      Nyomtat.Caption = langform(1)
      Nyomtat.Command1.Caption = langform(2)
      Nyomtat.Command2.Caption = langform(3)
      Nyomtat.Command3.Caption = langform(4)
      Nyomtat.Command4.Caption = langform(5)
      Nyomtat.Label2.Caption = langform(6)
      Nyomtat.Label1.Caption = langform(7)
      Nyomtat.Label4.Caption = langform(8)
      Nyomtat.Label5.Caption = langform(9)
      Nyomtat.Label3.Caption = langform(10)
    Case "prbeall"
      Prbeall.Caption = langform(1)
      Prbeall.Command4.Caption = langform(2)
      Prbeall.Command5.Caption = langform(3)
      Prbeall.Command6.Caption = langform(4)
      Prbeall.Option1.Caption = langform(5)
      Prbeall.Option2.Caption = langform(6)
      Prbeall.Option3.Caption = langform(7)
      Prbeall.Frame1.Caption = langform(8)
      Prbeall.Label3.Caption = langform(9)
      Prbeall.Label4.Caption = langform(10)
      Prbeall.Label5.Caption = langform(11)
      Prbeall.Label11.Caption = langform(11)
      Prbeall.Label6.Caption = langform(12)
      Prbeall.Label12.Caption = langform(12)
      Prbeall.Label7.Caption = langform(13)
      Prbeall.Label8.Caption = langform(14)
      Prbeall.Label9.Caption = langform(15)
      Prbeall.Label10.Caption = langform(16)
    Case "nomseg"
      Nomseg.Caption = langform(1)
      Nomseg.Command1.Caption = langform(2)
    Case "becsom"
      becsom.Caption = langform(1)
    Case "dokfull"
      Dokfull.Caption = langform(1)
    Case "dokopt"
      Dokopt.Caption = langform(1)
    Case "partnev"
      Partnev.Label1.Caption = langform(1)
      Partnev.Label2.Caption = langform(2)
      Partnev.Label3.Caption = langform(3)
      Partnev.Label4.Caption = langform(4)
      Partnev.Label5.Caption = langform(5)
      Partnev.Label6.Caption = langform(6)
      Partnev.Command1.Caption = langform(7)
      Partnev.Command2.Caption = langform(8)
      Partnev.Caption = langform(9)
    Case "cikknev"
      cikknev.Caption = langform(1)
      cikknev.Label1.Caption = langform(2)
      cikknev.Label2.Caption = langform(3)
      cikknev.Label4.Caption = langform(5)
      cikknev.Command1.Caption = langform(4)
    Case "auw-adm"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Command3.Caption = langform(3)
      form1.Command4.Caption = langform(4)
      form1.Command5.Caption = langform(5)
      form1.Command6.Caption = langform(6)
      form1.Command7.Caption = langform(7)
      form1.Command8.Caption = langform(8)
      form1.Command9.Caption = langform(9)
      form1.Command10.Caption = langform(10)
      form1.Command1.ToolTipText = langform(11)
      form1.Command2.ToolTipText = langform(12)
      form1.Command3.ToolTipText = langform(13)
      form1.Command4.ToolTipText = langform(14)
      form1.Command5.ToolTipText = langform(15)
      form1.Command6.ToolTipText = langform(16)
      form1.Command7.ToolTipText = langform(17)
      form1.Command8.ToolTipText = langform(18)
      form1.Command9.ToolTipText = langform(19)
      form1.Command10.ToolTipText = langform(20)
      form1.Label5.Caption = langform(21)
      form1.Label4.Caption = langform(22)
    Case "auw-armg"
      form1.Command1.Caption = langform(1)
      form1.Command18.Caption = langform(15)
      form1.Command2.Caption = langform(2)
      form1.Command21.Caption = langform(18)
      form1.Command3.Caption = langform(3)
      form1.Command4.Caption = langform(4)
      form1.Command5.Caption = langform(5)
      form1.Command6.Caption = langform(6)
      form1.Command7.Caption = langform(7)
      form1.Frame6.Caption = langform(16)
      form1.Frame7.Caption = langform(17)
      form1.Frame8.Caption = langform(1)
      form1.Command1.ToolTipText = langform(8)
      form1.Command2.ToolTipText = langform(9)
      form1.Command3.ToolTipText = langform(10)
      form1.Command4.ToolTipText = langform(11)
      form1.Command5.ToolTipText = langform(12)
      form1.Command6.ToolTipText = langform(13)
      form1.Command7.ToolTipText = langform(14)
    Case "auw-dvrf"
      form1.Command1.Caption = langform(2)
      form1.Command4.Caption = langform(1)
      form1.Command1.ToolTipText = langform(4)
      form1.Command4.ToolTipText = langform(3)
      form1.Text3.ToolTipText = langform(5)
      form1.Label4.Caption = langform(6)
      form1.Label5.Caption = langform(7)
    Case "auw-ealp"
      form1.Command1.Caption = langform(1)
      form1.Label4.Caption = langform(2)
      form1.Label6.Caption = langform(3)
      form1.Label5.Caption = langform(4)
    Case "auw-ean", "auw-fffl", "auw-fkiv", "auw-fkrt", "auw-fmrg", "auw-fnp", "auw-kfan", "auw-kkim", "auw-kkrt", "auw-pafa", "auw-pan", "auw-pel", "auw-pkom", "auw-pkiv", "auw-pvtl", "auw-ptrv", "auw-pkam", "auw-pkrt", "auw-pkrt"
      form1.Command1.Caption = langform(1)
      form1.Label4.Caption = langform(2)
      form1.Label6.Caption = langform(3)
      form1.Label5.Caption = langform(4)
    Case "auw-ekrt"
      form1.Command1.Caption = langform(1)
      form1.Label4.Caption = langform(2)
      form1.Label6.Caption = langform(3)
      form1.Label5.Caption = langform(4)
    Case "auw-elle"
      form1.Check1.Caption = langform(1)
      form1.Check2.Caption = langform(2)
      form1.Check3.Caption = langform(3)
      form1.Check4.Caption = langform(4)
      form1.Check5.Caption = langform(5)
      form1.Check6.Caption = langform(6)
      form1.Check7.Caption = langform(7)
      form1.Check8.Caption = langform(8)
      form1.Check9.Caption = langform(9)
      form1.Check10.Caption = langform(10)
      form1.Check11.Caption = langform(11)
      form1.Check12.Caption = langform(12)
      form1.Check13.Caption = langform(13)
      form1.Check14.Caption = langform(14)
      form1.Check15.Caption = langform(15)
      form1.Check16.Caption = langform(16)
      form1.Check17.Caption = langform(17)
      form1.Check18.Caption = langform(18)
      form1.Check19.Caption = langform(19)
      form1.Check20.Caption = langform(20)
      form1.Check21.Caption = langform(21)
      form1.Check22.Caption = langform(22)
      form1.Check42.Caption = langform(23)
      form1.Check43.Caption = langform(24)
      form1.Frame3.Caption = langform(25)
      form1.Frame4.Caption = langform(26)
      form1.Label7.Caption = langform(27)
      form1.Command2.Caption = langform(28)
      form1.Command1.Caption = langform(29)
    Case "auw-eslk"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Command3.Caption = langform(3)
      form1.Command4.Caption = langform(4)
      form1.Command5.Caption = langform(5)
      form1.Command1.ToolTipText = langform(6)
      form1.Text3.Text = langform(7)
    Case "auw-fcse", "auw-ffog"
      form1.Command1.Caption = langform(2)
      form1.Command2.Caption = langform(1)
    Case "auw-fezr"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Frame1.Caption = langform(3)
      form1.Label7.Caption = langform(4)
    Case "auw-fkvl", "auw-fris"
      form1.Caption = langform(1)
      form1.Label2.Caption = langform(1)
      form1.Command1.Caption = langform(2)
      form1.Command2.Caption = langform(3)
    Case "auw-fvrg"
      form1.Frame1.Caption = langform(1)
      form1.Label7.Caption = langform(2)
      form1.Label8.Caption = langform(3)
    Case "auw-fvlk"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Command3.Caption = langform(3)
      form1.Command4.Caption = langform(4)
      form1.MSFlexGrid3.ToolTipText = langform(5)
      form1.MSFlexGrid4.ToolTipText = langform(6)
      form1.MSFlexGrid5.ToolTipText = langform(7)
    Case "auw-init"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Check1.Caption = langform(3)
      form1.Check2.Caption = langform(4)
      form1.Check3.Caption = langform(5)
      form1.Check4.Caption = langform(6)
      form1.Frame1.Caption = langform(7)
      form1.Frame2.Caption = langform(8)
      form1.Label7.Caption = langform(9)
      form1.Label10.Caption = langform(10)
      form1.Option1.Caption = langform(11)
      form1.Option2.Caption = langform(12)
      form1.Option3.Caption = langform(13)
      form1.Option5.Caption = langform(14)
    Case "auw-izar"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Frame1.Caption = langform(3)
      form1.Frame2.Caption = langform(4)
      form1.Label4.Caption = langform(5)
      form1.Label7.Caption = langform(6)
      form1.Option1.Caption = langform(7)
      form1.Option2.Caption = langform(8)
      form1.Option3.Caption = langform(9)
      form1.Option4.Caption = langform(10)
      form1.Option5.Caption = langform(11)
      form1.Option6.Caption = langform(12)
      form1.Option7.Caption = langform(13)
      form1.Option8.Caption = langform(14)
    Case "auw-pbnk"
      form1.Command1.Caption = langform(1)
      form1.Command3.Caption = langform(2)
      form1.Label5.Caption = langform(3)
      form1.Label4.Caption = langform(4)
    Case "auw-pflk"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Command3.Caption = langform(3)
      form1.Command4.Caption = langform(4)
      form1.Command5.Caption = langform(5)
      form1.Command6.Caption = langform(6)
      form1.Command7.Caption = langform(7)
      form1.MSFlexGrid3.ToolTipText = langform(8)
      form1.MSFlexGrid4.ToolTipText = langform(9)
      form1.MSFlexGrid5.ToolTipText = langform(10)
    Case "auw-pkrg"
      form1.Command1.Caption = langform(1)
      form1.Command4.Caption = langform(2)
      form1.Command5.Caption = langform(3)
      form1.Command6.Caption = langform(4)
      form1.Label4.Caption = langform(5)
      form1.Command21.Caption = langform(6)
      form1.Command22.Caption = langform(7)
      form1.Command23.Caption = langform(8)
    Case "auw-pszl"
      form1.Command1.Caption = langform(1)
      form1.Command3.Caption = langform(2)
      form1.Label5.Caption = langform(3)
      form1.Label4.Caption = langform(4)
    Case "auw-ptrg"
      form1.Command1.Caption = langform(1)
      form1.Command3.Caption = langform(2)
      form1.Label5.Caption = langform(3)
      form1.Label4.Caption = langform(4)
    Case "auw-pvlk"
      form1.Command1.Caption = langform(1)
      form1.Label7.Caption = langform(2)
      form1.Label8.Caption = langform(3)
    Case "auw-pvrg"
      form1.Command1.Caption = langform(1)
      form1.Command4.Caption = langform(2)
      form1.Label4.Caption = langform(3)
    Case "auw-kksl"
      form1.Command1.Caption = langform(1)
      form1.Command3.Caption = langform(2)
      form1.Command4.Caption = langform(3)
    Case "auw-rks", "auw-rfan", "auw-rmus", "auw-rmls", "auw-rlls", "auw-rstt", "auw-rsbt", "auw-ralp", "auw-rht", "auw-rkrt"
      form1.Command1.Caption = langform(1)
      form1.Label4.Caption = langform(2)
      form1.Label6.Caption = langform(3)
      form1.Label5.Caption = langform(4)
    Case "auw-rlel"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Command3.Caption = langform(3)
      form1.Command4.Caption = langform(4)
      form1.Command5.Caption = langform(5)
      form1.Label5.Caption = langform(6)
    Case "auw-rnyi"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Command3.Caption = langform(3)
      form1.Command4.Caption = langform(4)
      form1.Command5.Caption = langform(5)
      form1.Command6.Caption = langform(6)
      form1.Command7.Caption = langform(7)
      form1.Command8.Caption = langform(8)
      form1.Option1.Caption = langform(9)
      form1.Option2.Caption = langform(10)
      form1.Label7.Caption = langform(11)
      form1.Label8.Caption = langform(14)
      form1.Frame2.Caption = langform(12)
      form1.Frame3.Caption = langform(13)
      form1.Check1.Caption = langform(15)
      form1.Check2.Caption = langform(16)
      form1.Check3.Caption = langform(17)
      form1.Check4.Caption = langform(18)
      form1.Check5.Caption = langform(19)
      form1.Check6.Caption = langform(20)
      form1.Check7.Caption = langform(21)
      form1.Check8.Caption = langform(22)
      form1.Check9.Caption = langform(23)
      form1.Check10.Caption = langform(24)
      form1.Check11.Caption = langform(25)
      form1.Check12.Caption = langform(26)
      form1.Check13.Caption = langform(27)
      form1.Check14.Caption = langform(28)
      form1.Check15.Caption = langform(29)
      form1.Check16.Caption = langform(30)
      form1.Check17.Caption = langform(31)
      form1.Text9.Text = langform(32) + Chr$(13) + Chr$(10) + langform(33) + Chr$(13) + Chr$(10) + langform(34) + Chr$(13) + Chr$(10) + langform(35) + Chr$(13) + Chr$(10) + langform(36) + Chr$(13) + Chr$(10) + langform(37)
    Case "auw-rfrp"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Command5.Caption = langform(3)
      form1.Command6.Caption = langform(4)
      form1.Command7.Caption = langform(5)
      form1.Command8.Caption = langform(6)
      form1.Label7.Caption = langform(7)
      form1.Label8.Caption = langform(8)
      form1.Label20.Caption = langform(9)
      form1.Command20.Caption = langform(10)
      form1.Command19.Caption = langform(11)
    Case "auw-rrrk"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Command5.Caption = langform(3)
      form1.Command6.Caption = langform(4)
      form1.Command7.Caption = langform(5)
      form1.Command8.Caption = langform(6)
      form1.Label7.Caption = langform(7)
      form1.Label8.Caption = langform(8)
    Case "auw-rmeg"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Command3.Caption = langform(3) + " " + langform(6)
      form1.Command4.Caption = langform(4)
      form1.Command5.Caption = langform(5)
      form1.Frame1.Caption = langform(3) + " " + langform(6)
      form1.Label7.Caption = langform(7)
    Case "auw-rmlk"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Command3.Caption = langform(3)
      form1.Command4.Caption = langform(4)
    Case "auw-rslk"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Command3.Caption = langform(3)
      form1.Command4.Caption = langform(4)
      form1.Command5.Caption = langform(5)
      form1.Command6.Caption = langform(6)
      form1.Command7.Caption = langform(7)
      form1.Command8.Caption = langform(8)
      form1.Command9.Caption = langform(9)
      form1.Command10.Caption = langform(10)
      form1.Command11.Caption = langform(11)
      form1.Command12.Caption = langform(12)
    Case "auw-rszl"
      form1.Command1.Caption = langform(1)
      form1.Command3.Caption = langform(2)
      form1.Command4.Caption = langform(3)
      form1.Command5.Caption = langform(4)
      form1.Command6.Caption = langform(5)
      form1.Command7.Caption = langform(6)
      form1.Command8.Caption = langform(7)
      form1.Label4.Caption = langform(8)
      form1.Label5.Caption = langform(9)
      form1.Label7.Caption = langform(10)
    Case "auw-rjov"
      form1.Command1.Caption = langform(1)
      form1.Command4.Caption = langform(2)
      form1.Label4.Caption = langform(3)
      form1.Label5.Caption = langform(4)
      form1.Label7.Caption = langform(5)
      form1.Command5.Caption = langform(6)
    Case "auw-rgyj"
      form1.Command1.Caption = langform(1)
      form1.Command5.Caption = langform(2)
      form1.Label4.Caption = langform(3)
      form1.Label6.Caption = langform(4)
      form1.Label5.Caption = langform(5)
      form1.Label7.Caption = langform(6)
    Case "dbx4-chn"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Check1.Caption = langform(3)
      form1.Check2.Caption = langform(4)
      form1.Option1.Caption = langform(5)
      form1.Option2.Caption = langform(6)
      form1.Label3.Caption = langform(7)
      form1.Label4.Caption = langform(8)
      form1.Label14.Caption = langform(9)
      form1.Label9.Caption = langform(10)
      form1.Frame1.Caption = langform(11)
      form1.Label2.Caption = langform(12)
      form1.Caption = langform(12)
    Case "dbx4-org"
      form1.Caption = langform(1)
      form1.Label2.Caption = langform(1)
      form1.Label1.Caption = langform(2)
      form1.Label11.Caption = langform(3)
      form1.Label3.Caption = langform(4)
      form1.Label4.Caption = langform(5)
      form1.Label5.Caption = langform(6)
      form1.Label9.Caption = langform(7)
      form1.Option1.Caption = langform(8)
      form1.Option2.Caption = langform(9)
      form1.Check1.Caption = langform(10)
      form1.Check2.Caption = langform(11)
      form1.Command1.Caption = langform(12)
      form1.Command2.Caption = langform(13)
    Case "dbx4-sho"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Command3.Caption = langform(3)
      form1.Command4.Caption = langform(4)
      form1.Command5.Caption = langform(5)
      form1.Command6.Caption = langform(6)
      form1.Command7.Caption = langform(7)
      form1.Command8.Caption = langform(8)
      form1.Command9.Caption = langform(9)
      form1.Command10.Caption = langform(10)
      form1.Command11.Caption = langform(11)
      form1.Command12.Caption = langform(12)
      form1.Command13.Caption = langform(13)
      form1.Command14.Caption = langform(14)
      form1.Command15.Caption = langform(15)
      form1.Label1.Caption = langform(16)
      form1.Label10.Caption = langform(17)
      form1.Label11.Caption = langform(18)
      form1.Label3.Caption = langform(19)
      form1.Label4.Caption = langform(20)
      form1.Label5.Caption = langform(21)
      form1.Label6.Caption = langform(22)
      form1.Label7.Caption = langform(23)
      form1.Label8.Caption = langform(24)
      form1.Label9.Caption = langform(25)
    Case "dbx4-lst"
      form1.Caption = langform(1)
      form1.Label1.Caption = langform(1)
      form1.Command1.Caption = langform(2)
      form1.Command2.Caption = langform(3)
      form1.Command3.Caption = langform(4)
      form1.Command4.Caption = langform(5)
      form1.Frame1.Caption = langform(6)
      form1.Label2.Caption = langform(7)
      form1.Label3.Caption = langform(8)
      form1.Label4.Caption = langform(9)
      form1.Label5.Caption = langform(10)
      form1.Label6.Caption = langform(11)
      form1.Label7.Caption = langform(12)
      form1.Label8.Caption = langform(13)
      form1.Option1.Caption = langform(14)
      form1.Option2.Caption = langform(15)
      form1.MSFlexGrid1.ToolTipText = langform(16)
      form1.MSFlexGrid2.ToolTipText = langform(17)
    Case "auw-ujf"
      form1.Check1.Caption = langform(1)
      form1.Check2.Caption = langform(2)
      form1.Command1.Caption = langform(3)
      form1.Command2.Caption = langform(4)
      form1.Label2.Caption = langform(5)
      form1.Caption = langform(5)
      form1.Label11.Caption = langform(6)
      form1.Label14.Caption = langform(7)
      form1.Label3.Caption = langform(8)
      form1.Label4.Caption = langform(9)
      form1.Label9.Caption = langform(10)
      form1.Option3.Caption = langform(11)
      form1.Option4.Caption = langform(12)
      form1.Option5.Caption = langform(13)
      form1.Option6.Caption = langform(14)
      form1.Frame3.Caption = langform(15)
    Case "auw-uny"
      form1.Command1.Caption = langform(1)
      form1.Command2.Caption = langform(2)
      form1.Command5.Caption = langform(3)
    Case "auw-web"
      form1.Check1.Caption = langform(8)
      form1.Check2.Caption = langform(9)
      form1.Check3.Caption = langform(10)
      form1.Check4.Caption = langform(11)
      form1.Command1.Caption = langform(12)
      form1.Command2.Caption = langform(13)
      form1.Command3.Caption = langform(14)
      form1.Caption = langform(15)
      form1.Frame1.Caption = langform(16)
      form1.Frame2.Caption = langform(17)
      form1.Label1.Caption = langform(18)
      form1.Label2.Caption = langform(19)
    Case "auw-ment"
      form1.Check1.Caption = langform(1)
      form1.Check2.Caption = langform(2)
      form1.Check3.Caption = langform(3)
      form1.Check4.Caption = langform(4)
      form1.Check5.Caption = langform(5)
      form1.Check6.Caption = langform(6)
      form1.Command1.Caption = langform(7)
      form1.Command2.Caption = langform(8)
      form1.Command3.Caption = langform(9)
      form1.Label2.Caption = langform(10)
      form1.Caption = langform(10)
      form1.Frame1.Caption = langform(11)
      form1.Frame2.Caption = langform(12)
      form1.Frame3.Caption = langform(13)
      form1.Frame4.Caption = langform(13)
      form1.Frame5.Caption = langform(14)
      form1.Label10.Caption = langform(15)
      form1.Label11.Caption = langform(16)
      form1.Label13.Caption = langform(17)
      form1.Label14.Caption = langform(18)
      form1.Label9.Caption = langform(19)
      form1.Option1.Caption = langform(20)
      form1.Option10.Caption = langform(21)
      form1.Option11.Caption = langform(22)
      form1.Option2.Caption = langform(23)
      form1.Option5.Caption = langform(24)
      form1.Option6.Caption = langform(25)
      form1.Option7.Caption = "C:\auwin\mentes " + langform(26)
      form1.Option8.Caption = langform(27)
      form1.Option9.Caption = "C:\auwin\mentes " + langform(28)
    Case "dbx4-out"
      form1.Check1.Caption = langform(1)
      form1.Check2.Caption = langform(2)
      form1.Command1.Caption = langform(3)
      form1.Command2.Caption = langform(4)
      form1.Label1.Caption = langform(5)
      form1.Label4.Caption = langform(6)
      form1.Option1.Caption = langform(7)
      form1.Option4.Caption = langform(8)
      form1.Option5.Caption = langform(9)
      form1.Option6.Caption = langform(10)
    Case "dbx4-exp"
      form1.Label7.Caption = langform(1)
      form1.Label8.Caption = langform(2)
      form1.Label4.Caption = langform(3)
      form1.Label5.Caption = langform(4)
      form1.Label6.Caption = langform(5)
      form1.Command3.Caption = langform(6)
      form1.Command2.Caption = langform(7)
      form1.Command4.Caption = langform(8)
      form1.Command1.Caption = langform(9)
    Case Else
  End Select
End Sub

Public Sub scpar(sor$, hatarolo$)
  '--- sor paraméterek szétválasztása
  For p% = 1 To 10: spar$(p%) = " ": Next
  x$ = sor$
  spdb% = 0
  Do
    p% = InStr(x$, hatarolo)
    If p% > 0 Then
      spdb% = spdb% + 1
      spar$(spdb%) = Left$(x$, p% - 1)
      x$ = Mid$(x$, p% + 1)
    Else
      If Len(x$) > 0 Then
        spdb% = spdb% + 1
        spar$(spdb%) = x$
        x$ = ""
      End If
    End If
  Loop While Len(x$) > 0
End Sub

